// // Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// // Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// // copy, distribute and modify it.

// // AWS Mobile Hub Project Constants
// const awsmobile = {
//     aws_app_analytics : 'enable',
//     aws_cognito_identity_pool_id : 'us-east-1:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',
//     aws_cognito_region : 'us-east-1',
//     aws_content_delivery : 'enable',
//     aws_content_delivery_bucket : 'XXXXXX-hosting-mobilehub-1234567890',
//     aws_content_delivery_bucket_region : 'us-east-1',
//     aws_content_delivery_cloudfront : 'enable',
//     aws_content_delivery_cloudfront_domain : 'XXXXXXXXXXX.cloudfront.net',
//     aws_mobile_analytics_app_id : 'XXXXXXXXXXXXXXXXXXXXXXX',
//     aws_project_id : XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX ',
//     aws_project_name : 'XXXXXX’,
//     aws_project_region : 'us-east-1',
//     aws_resource_name_prefix : 'XXXXXX-mobilehub-1234567890’,
//     }
    
//     export default awsmobile;
//     var AWS = require('aws-sdk');
//     AWS.config.region = awsmobile.aws_project_region;
//     AWS.config.update({customUserAgent: 'MobileHub v0.1'});